### ISSUE TITLE
REST between two dates returns 'bad request'

### ISSUE THREAD

**Issue by discountscott** [xtuple/xtuple#2033]
Trying to make a GET on the receivables with 'documentDate' between two values. I receive 'bad request'.

If works if I remove the second parameter (AT_MOST). But I need to query on the receivables between two dates.

I'm using the following:

```json
/resources/receivable?query[documentDate][AT_LEAST]=2014-10-01&query[documentDate][AT_MOST]=2014-10-31&query[documentType][NOT_EQUALS]=I
```

**Comment by bendiy** [comment]
@discountscott 
This has been fixed in `4_10_x` using the new [restQueryFormat](https://github.com/xtuple/xtuple/blob/4_10_x/node-datasource/routes/restRouter.js#L7). Here is a URL that will make a date range request on Incidents:
```
https://example.com/db-name-here/api/v1alpha1/resources/incident-list-item?query[created][AT_LEAST]=2001-01-01&query[created][AT_MOST]=2015-12-31&orderby[number]=DESC&orderby[status]=ASC&maxresults=10&pagetoken=0
```

Please reopen this issue if you are still having problems in `4_10_x`.
