### ISSUE TITLE
Enyo input fields do not map to the correct mobile keyboard

### ISSUE THREAD

**Issue by bendiy** [xtuple/xtuple#2161]
We should be doing this for numbers and emails, but still end up with the default text keyboard on mobile devices:
http://developer.lge.com/webOSTV/develop/web-app/how/use-virtual-keyboard/

It works fine here: 
Enyo Core > UI > Input > Number Input:
http://enyojs.com/sampler/latest/

**Comment by jcarlin** [comment]
Implementing `type: "DecimalInput"` because `type: number` adds an up/down toggle inside the input and I didn't think we wanted that, it's too small to use anyway. http://forums.enyojs.com/discussion/1466/resticting-oynx-input-to-numeric-only

I tried modifying email inputs to `type: "email"` but that errors here: https://github.com/xtuple/enyo/blob/master/source/ui/Input.js#L132. Error: 
> Uncaught InvalidStateError: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('email') does not support selection.

That could be patched with something like:
> var html5types = ['password', 'email', 'url', 'tel', 'number', 'range', 'time'];
    if (html5types.indexOf(n.type) == -1 && n.setSelectionRange) {
        ...
... but it's in enyo source so maybe it's best just to leave email as (default) `type: "text"` for now.

**Comment by bendiy** [comment]
https://github.com/xtuple/xtuple/pull/2167

**Comment by bendiy** [comment]
@jcarlin: On Issue Stock, the `To Issue:` field I'm testing is still giving me the Android text keyboard, not numeric.
