### ISSUE TITLE
Issue Material list multi-select not working properly

### ISSUE THREAD

**Issue by jcarlin** [xtuple/xtuple#2188]
![issue-multi-select_720](https://cloud.githubusercontent.com/assets/1823527/6175695/99d2f528-b2be-11e4-8f99-aa5702a5676f.png)

**Comment by bendiy** [comment]
@jcarlin: I'm not sure what's supposed to happen when you multi-select lines and then choose `Issue Material` on one line. If it's going to loop through each line, it's very confusing to the end user because it doesn't go to the line the click `Issue Material` on first, but could go to the line above. 

Do we actually support selecting multiple lines here or should we un-select any other lines when you select one?

**Comment by jcarlin** [comment]
We do support multi-select for inventory transactions. It is broken here. It should cycle through all that were selected and I agree that it should start on the highlighted line.

**Comment by bendiy** [comment]
It should start from the line you selected the gear on, not the first in the list. I really don't like the UX here because it's easy to select a line and then select another without knowing you have multiple lines selected. Especially if the list is long and items are off the screen. I think fixing it so the first item it goes to is the one you selected the gear on will help, but overall, the multi-select is confusing.

I think multi-select actions should only be supported through the `Actions` gear in the top left, not the individual line gear. When selecting an individual line gear, I'd expect that action to only take place on that line, not any other random lines that might be selected. Gmail has multi-select actions at the top of the list, not on the line. We should add an `Issue selected lines` to the main left Action gear.
![multi-select](https://cloud.githubusercontent.com/assets/571574/6219032/066c0514-b5e2-11e4-8098-31b521140e47.png)

**Comment by jcarlin** [comment]
Multi-select is now disabled across the app in small devices. https://github.com/xtuple/xtuple/pull/2390. Closing this issue but there are still some valid UX comments here regarding action gear buttons and multi-select.
