### ISSUE TITLE
Scanning a lot barcode distributes qty 1 to lot as well

### ISSUE THREAD

**Issue by jcarlin** [xtuple/xtuple#2208]
Issue to shipping Item List should support scanning a lot barcode to auto issue one qty for each scan. Order qty of 5 would require just 5 lot # barcode scans. From the list of items, you can scan Lot # or Item number barcodes (for non-lot items) to issue 1 qty of that item. Each barcode scan would issue 1 qty. The only time you need to drill down into the item detail workspace is if you want to issue multiple qty at once because scanning 100+ barcodes would be impractical.

When an item is first scanned, the stock status should indicate that "some inventory" is issued, but not complete. The qty issued on the list should auto update as this happens.

Once the full line qty has been scanned, stock status should indicate that the line is fully issued. Any additional scans for that item would present user with error `This line item is complete. Cannot issue any more stock to it.`.

![issue-list-scanning](https://cloud.githubusercontent.com/assets/571574/6217523/2929f3c8-b5d2-11e4-8704-e3bc21bef8f7.png)

**Comment by bendiy** [comment]
This is a UX issue because the goals for mobile inventory and barcodes is to reduce user interaction and input. When this is fixed, a user should be able to bring up the Issue to Shipping list and do everything before shipping the order with only barcode scans, like at a grocery store. Having to constantly stop to switch screens and hand enter data makes the current process very inefficient.

**Comment by jcarlin** [comment]
Unless we have more intelligent, new barcodes, there is no way to avoid requiring at least an item (item number or UPC) barcode scan before lot/location scans. We should require an item scan, it makes sense.
